# Generated by Django 5.2.7 on 2025-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_age_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sleep_time',
            field=models.TimeField(blank=True, help_text='Daily sleep time', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wake_time',
            field=models.TimeField(blank=True, help_text='Daily wake up time', null=True),
        ),
    ]
