# Generated by Django 5.2.7 on 2025-10-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_sleep_time_user_wake_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sleep_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wake_time',
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
