# Generated by Django 5.2.7 on 2025-10-26 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='growth_stage',
            field=models.IntegerField(choices=[(1, 'Seed'), (2, 'Sprout'), (3, 'Young Plant'), (4, 'Mature Plant')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
