# Generated by Django 5.2.7 on 2025-10-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_fixedschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'priority']},
        ),
        migrations.DeleteModel(
            name='FixedSchedule',
        ),
    ]
