# Generated by Django 5.2.7 on 2025-10-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_delete_fixedschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scheduled_start',
        ),
    ]
