# Generated by Django 5.2.7 on 2025-10-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_scheduled_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_time_minutes',
        ),
    ]
