# Generated by Django 5.2.7 on 2025-10-26 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.IntegerField(choices=[(1, 'Seed'), (2, 'Sprout'), (3, 'Seedling'), (4, 'Young Plant'), (5, 'Mature Plant')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('water_drops', models.IntegerField(default=0)),
                ('water_progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'minigame_plant',
            },
        ),
        migrations.CreateModel(
            name='WaterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_spent', models.IntegerField()),
                ('water_drops_received', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Transaction',
                'verbose_name_plural': 'Water Transactions',
                'db_table': 'minigame_water_transaction',
                'ordering': ['-timestamp'],
            },
        ),
    ]
